apiVersion: v1
kind: Config
clusters:
- name: "student"
  cluster:
    server: "https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h"

users:
- name: "student"
  user:
    token: "kubeconfig-u-y4d4dgdylqd75rx:xp2bjjx5hjcll7l2vxczhl64gd6gdzrlhkf924dgsgrf4h5g48f27s"

contexts:
- name: "student"
  context:
    user: "student"
    cluster: "student"

current-context: "student"
