{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "client-app.fullname" . }}
  labels:
    {{- include "client-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "client-app.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /()(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "client-app.fullname" . }}
              port:
                number: {{ .Values.service.port }}

        - path: /api/auth(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: authentication-service
              port:
                number: 8080

        - path: /api/courses(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: course-service
              port:
                number: 8080
