{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "client-app.fullname" . }}
  labels:
    {{- include "client-app.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "client-app.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "client-app.fullname" . }}
              port:
                number: {{ .Values.service.port }}
 
 
        # Direct routes (without /api prefix) 
        - path: /auth/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: authentication-service
              port:
                number: 8080

        - path: /courses/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: course-service
              port:
                number: 8080

        - path: /categories/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: course-service
              port:
                number: 8080

        - path: /reviews/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: review-service
              port:
                number: 8080

        - path: /categories(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: course-service
              port:
                number: 8080

        - path: /reviews(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: review-service
              port:
                number: 8080

        - path: /api/recommendation(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: recommendation-gateway
              port:
                number: 8080
{{- end }}
